# Generated by Django 6.0.2 on 2026-04-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Tasks',
        ),
    ]
